"""init

Revision ID: 5be2c3ab27d6
Revises:
Create Date: 2026-02-10 14:45:42.139453

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5be2c3ab27d6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consultation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("text_length", sa.Integer(), nullable=False),
        sa.Column("was_anonymized", sa.Boolean(), nullable=False),
        sa.Column("ontology_version", sa.String(length=50), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("summary_generated_by", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_consultation_runs_created_at",
        "consultation_runs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("domain_id", sa.String(length=20), nullable=False),
        sa.Column("domain_name", sa.String(length=200), nullable=False),
        sa.Column("symptom", sa.String(length=200), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("negated", sa.Boolean(), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["consultation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_run_id"), "findings", ["run_id"], unique=False)
    op.create_table(
        "gaps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("domain_id", sa.String(length=20), nullable=False),
        sa.Column("domain_name", sa.String(length=200), nullable=False),
        sa.Column("gap_level", sa.String(length=10), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "suggested_questions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["consultation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gaps_run_id"), "gaps", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gaps_run_id"), table_name="gaps")
    op.drop_table("gaps")
    op.drop_index(op.f("ix_findings_run_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index("ix_consultation_runs_created_at", table_name="consultation_runs")
    op.drop_table("consultation_runs")
    # ### end Alembic commands ###
