global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:${PORT}"]

  - job_name: neurorelato-backend
    scheme: https
    metrics_path: /metrics
    basic_auth:
      username: ${PN_METRICS_BASIC_AUTH_USER}
      password: ${PN_METRICS_BASIC_AUTH_PASSWORD}
    static_configs:
      # Host do app principal (sem https://). Ex: neurorelatopoc-xxxx.herokuapp.com
      - targets: ["${PN_METRICS_TARGET}"]
